// oxycash-rs - ui/palette.slint

export global Palette {
    in-out property <color> bg:          #0D0D0D;
    in-out property <color> bg2:         #131311;
    in-out property <color> card:        #161614;
    in-out property <color> card-border: #222220;
    in-out property <color> text:        #E8E4DE;
    in-out property <color> text2:       #9A9690;
    in-out property <color> text3:       #4A4744;
    in-out property <color> red:         #D96459;
    in-out property <color> teal:        #85CDCA;
    in-out property <color> gold:        #E8A87C;
    in-out property <color> green:       #7BC47F;
    in-out property <color> danger:      #E05555;
    in-out property <color> amber:       #F2D388;
    in-out property <color> brown:       #C7B198;
    in-out property <color> blue:        #6FA8DC;
    in-out property <color> purple:      #B794D6;
}
